# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only on pull for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: dev

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  test:
    strategy:
      matrix:
        go-version: [1.16.x]
        os: [ubuntu-latest, macos-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
    - name: Install Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}

    - name: Install Chrome
      uses: browser-actions/setup-chrome@latest

    - name: Checkout code
      uses: actions/checkout@v2

    - name: Download dependencies
      run: go mod tidy

    # Runs a single command using the runners shell
    - name: Build
      run: go build ${{ github.action_path }}

    # Runs command using the runners shell
    - name: Show version
      run: ./aquasily -version
    
    - name: Run scan
      run: echo "scanme.nmap.org" | ./aquasily -debug
    
    - name: List content inside aquasilyReport dir
      run: ls -R aquasilyReport*
